ALTER TABLE public.page_views ADD COLUMN IF NOT EXISTS utm_source text;
ALTER TABLE public.page_views ADD COLUMN IF NOT EXISTS utm_medium text;
ALTER TABLE public.page_views ADD COLUMN IF NOT EXISTS utm_campaign text;

CREATE TABLE public.analytics_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  path text NOT NULL,
  referrer text,
  device text,
  browser text,
  os text,
  country text,
  region text,
  city text,
  language text,
  screen_size text,
  timezone text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  visitor_hash text,
  metadata jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

GRANT SELECT, INSERT ON public.analytics_events TO authenticated;
GRANT SELECT, INSERT ON public.analytics_events TO anon;
GRANT ALL ON public.analytics_events TO service_role;

ALTER TABLE public.analytics_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can insert analytics events"
  ON public.analytics_events
  FOR INSERT
  TO anon, authenticated
  WITH CHECK (
    (name IS NOT NULL) AND (length(name) <= 128)
    AND (path IS NOT NULL) AND (length(path) <= 2048)
    AND ((referrer IS NULL) OR (length(referrer) <= 2048))
    AND ((device IS NULL) OR (length(device) <= 64))
    AND ((browser IS NULL) OR (length(browser) <= 64))
    AND ((os IS NULL) OR (length(os) <= 64))
    AND ((country IS NULL) OR (length(country) <= 128))
    AND ((region IS NULL) OR (length(region) <= 128))
    AND ((city IS NULL) OR (length(city) <= 128))
    AND ((language IS NULL) OR (length(language) <= 32))
    AND ((screen_size IS NULL) OR (length(screen_size) <= 32))
    AND ((timezone IS NULL) OR (length(timezone) <= 64))
    AND ((utm_source IS NULL) OR (length(utm_source) <= 128))
    AND ((utm_medium IS NULL) OR (length(utm_medium) <= 128))
    AND ((utm_campaign IS NULL) OR (length(utm_campaign) <= 128))
    AND ((visitor_hash IS NULL) OR (length(visitor_hash) <= 128))
  );

CREATE POLICY "Only service role can view analytics events"
  ON public.analytics_events
  FOR SELECT
  TO service_role
  USING (true);

GRANT ALL ON public.analytics_events TO authenticated;